development:
  adapter: postgresql
  encoding: unicode
  database: development13
  pool: 5
  host: localhost
  username: postgres
  password: postgres



staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 